# server.py
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from main import run_research_workflow
import os
os.environ["TAVILY_API_KEY"] = "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"

app = FastAPI(title="Smart Research Assistant API", version="1.0")

# Allow CORS (for Streamlit frontend)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class ResearchRequest(BaseModel):
    topic_query: str


@app.post("/research")
def run_research(request: ResearchRequest):
    """Run the complete LangGraph research workflow."""
    try:
        print(f"[API] Received research request: '{request.topic_query}'")
        
        # Execute the complete LangGraph workflow
        result = run_research_workflow(request.topic_query)
        
        # The PDF is now generated by formatter_agent in the workflow
        # All data is already in the result state
        
        # Return the complete workflow result
        return {
            "topic": request.topic_query,
            "final_summary": result.get("final_summary", ""),
            "pdf_path": result.get("pdf_path", ""),
            "analysis_result": result.get("analysis_result", {}),
            "validation_result": result.get("validation_result", {}),
            "formatted_report": result.get("formatted_report", {}),
            "raw_documents": result.get("raw_documents", []),
            "status": "completed"
        }
        
    except Exception as e:
        print(f"[API ERROR] Research workflow failed: {e}")
        return {
            "topic": request.topic_query,
            "error": str(e),
            "status": "failed"
        }


@app.get("/health")
def health_check():
    """Health check endpoint."""
    return {"status": "healthy", "service": "Smart Research Assistant API"}


@app.get("/")
def root():
    return {
        "message": "Smart Research Assistant API is running",
        "version": "1.0",
        "endpoints": {
            "POST /research": "Run research workflow",
            "GET /health": "Health check"
        }
    }